datastore:
  cached:
    # Explicit location of a cache directory root that can be shared
    # between multiple Butler instantiations. Without this the Butler
    # will use a new temporary location each time.
    # Instantiating a Butler from another Butler could propagate temporary
    # location. This can be left out or null used
    # to indicate a temporary directory.
    root: null
    expiry:
      # Expiry mode and associated threshold.
      # Options are:
      # - null (no expiry)
      # - disabled (no caching)
      # - files (threshold is number of files)
      # - datasets (threshold is number of datasets)
      # - size (threshold is size in bytes)
      # - age (threshold is oldest file in seconds)
      # Default for everyone is to limit the cache size to 4 datasets.
      mode: datasets
      threshold: 1000
    # Default cache value. This will be the default decision if no specific
    # match is found in the "cacheable" section later on.
    default: false
    # Use a dict over list to simplify merging logic.
    cacheable:
      # Disable generic storage classes
      Exposure: false
      ExposureF: false
      # isr cacheables
      bias: true
      dark: true
      flat: true
      bfk: true
      crosstalk: true
      post_isr_image: true
